showme_project/.gitignore

git ignore file added

---

showme_project/app/controllers/articles_controller.rb
showme_project/app/views/articles/_form.html.erb

added error display for forms

---

showme_project/app/controllers/articles_controller.rb
showme_project/app/models/article.rb
showme_project/app/views/articles/_form.html.erb
showme_project/app/views/articles/edit.html.erb

User create

---

showme_project/app/views/articles/_article.html.erb

Privledge fix

---

showme_project/app/controllers/articles_controller.rb
showme_project/app/models/article.rb
showme_project/app/views/articles/_article.html.erb
showme_project/app/views/layouts/application.html.erb
showme_project/db/migrate/20171011083646_add_name_to_user.rb
showme_project/db/migrate/20171011090101_add_author_to_article.rb
showme_project/db/schema.rb
showme_project/db/seeds.rb

added author to articles and author into the searchbar functionality

Username migration

---

showme_project/app/controllers/application_controller.rb
showme_project/app/controllers/articles_controller.rb
showme_project/app/controllers/static_controller.rb
showme_project/app/models/ability.rb
showme_project/app/views/articles/_article.html.erb
showme_project/config/routes.rb

Created and fixed homepage with functional index and correct show pages.

Static page

---

showme_project/Gemfile
showme_project/Gemfile.lock
showme_project/app/assets/stylesheets/application.scss

installed bootstrap-sass and made index page compatible

Bootstrap fix

---

showme_project/app/assets/stylesheets/application.css
showme_project/app/views/articles/show.html.erb

show page title and header in progress

---

showme_project/app/controllers/application_controller.rb
showme_project/app/controllers/articles_controller.rb
showme_project/app/controllers/static_controller.rb
showme_project/app/models/ability.rb
showme_project/app/models/application_record.rb
showme_project/app/models/article.rb
showme_project/app/models/user.rb

Added comments to models and controllers.

Modcontcomment

---

showme_project/app/assets/javascripts/users.coffee
showme_project/app/assets/stylesheets/application.scss
showme_project/app/assets/stylesheets/users.scss
showme_project/app/controllers/users_controller.rb
showme_project/app/helpers/users_helper.rb
showme_project/app/views/layouts/application.html.erb
showme_project/app/views/users/create.html.erb
showme_project/app/views/users/destroy.html.erb
showme_project/app/views/users/edit.html.erb
showme_project/app/views/users/index.html.erb
showme_project/app/views/users/new.html.erb
showme_project/app/views/users/show.html.erb
showme_project/app/views/users/update.html.erb
showme_project/config/routes.rb
showme_project/db/seeds.rb
showme_project/test/controllers/users_controller_test.rb

added additional page for admins to use administrative actions on user accounts

Admin powers

---

showme_project/app/assets/stylesheets/application.scss

fixed css syntax error

---

showme_project/app/assets/stylesheets/application.scss
showme_project/app/views/articles/edit.html.erb
showme_project/app/views/articles/new.html.erb
showme_project/app/views/articles/show.html.erb

give to jenny

---

showme_project/app/assets/javascripts/application.js
showme_project/app/assets/stylesheets/application.scss
showme_project/app/views/layouts/application.html.erb
showme_project/app/views/users/index.html.erb

fixed css and added support for jquery

Js styling

---

showme_project/app/controllers/articles_controller.rb
showme_project/app/controllers/users_controller.rb
showme_project/app/models/article.rb
showme_project/app/views/users/create.html.erb
showme_project/app/views/users/destroy.html.erb
showme_project/app/views/users/edit.html.erb
showme_project/app/views/users/index.html.erb
showme_project/app/views/users/new.html.erb
showme_project/app/views/users/show.html.erb
showme_project/app/views/users/update.html.erb

added comments to the user controller/model and the articles layout page

Commenting

---

showme_project/app/views/articles/show.html.erb

Fixed indentation and added twitter link.

Social link

---

showme_project/.gitignore
showme_project/Gemfile
showme_project/Gemfile.lock
showme_project/app/controllers/articles_controller.rb
showme_project/app/models/article.rb
showme_project/app/views/articles/_form.html.erb
showme_project/app/views/articles/show.html.erb
showme_project/config/environments/development.rb
showme_project/config/environments/production.rb
showme_project/db/migrate/20171013100718_add_additional_image_to_article.rb
showme_project/db/migrate/20171013110039_change_image_types_in_article.rb
showme_project/db/schema.rb

Added AWS storage to a new image item.

Aws attempt

---

showme_project/app/views/articles/show.html.erb

Fixed something

---

showme_project/Gemfile
showme_project/Gemfile.lock
showme_project/app/assets/javascripts/application.js
showme_project/app/assets/stylesheets/application.scss
showme_project/app/views/layouts/application.html.erb

added support for JQuery and JS

Javascript

---

showme_project/app/assets/stylesheets/application.scss
showme_project/app/views/articles/show.html.erb
showme_project/app/views/layouts/application.html.erb

Only added in lines to bottom of show, bottom of CSS and one line in head of application layout.

Transferred over working code to up to date branch.

---

showme_project/app/views/layouts/application.html.erb

Fixed redirection issue

---

showme_project/app/assets/stylesheets/application.scss
showme_project/app/views/articles/index.html.erb

fixed some css
